### ISSUE TITLE
Function "serviceAuthorizer" doesn't exist in this Service

### ISSUE THREAD

**Issue by harterc3** [fernando-mc/aws-http-api-node-cognito#4]
I was copying a good amount of your serverless.yml to try and get my Cognito user pool, client, and authorizer auto-generated but am getting this error when running `sls deploy`:
`Function "serviceAuthorizer" doesn't exist in this Service`

Copied from my serverless.yml:
```
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    ...
  httpApi:
    authorizers:
      serviceAuthorizer:
        type: COGNITO_USER_POOLS
        identitySource: $request.header.Authorization
        issuerUrl: 
          Fn::Join:
          - ''
          - - 'https://cognito-idp.'
            - '${opt:region, self:provider.region}'
            - '.amazonaws.com/'
            - Ref: serviceUserPool
        audience:
          - Ref: serviceUserPoolClient
...
resources:
  Resources:
    serviceUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: test-qrdz-users-${opt:stage, self:provider.stage}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    serviceUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: test-qrdz-user-pool-client-${opt:stage, self:provider.stage}
        AllowedOAuthFlows:
          - implicit
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - phone
          - email
          - openid
          - profile
          - aws.cognito.signin.user.admin
        UserPoolId:
          Ref: serviceUserPool
        CallbackURLs: 
          - https://localhost:3000
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false
        SupportedIdentityProviders: 
          - COGNITO
...
functions:
  get-user:
    handler: src/functions/users.getUser
    events:
      - http:
          method: get
          path: users/{id}
          authorizer: serviceAuthorizer
```

**Comment by harterc3** [comment]
Ended up creating serviceAuthorizer in my Resources section:
```
serviceAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: test-service-user-pool-authorizer-${opt:stage, self:provider.stage}
        RestApiId: { "Ref" : "ApiGatewayRestApi" }
        IdentitySource: method.request.header.Authorization
        Type: COGNITO_USER_POOLS
        ProviderARNs:
        - Fn::GetAtt: [serviceUserPool, Arn]
```
And then in each handler
```
authorizer:
  type: COGNITO_USER_POOLS
  authorizerId:
    Ref: serviceAuthorizer
```
